### ISSUE TITLE
Would like to know which scalabuild file to use for Scala tutorial application

### ISSUE THREAD

**Issue by reynoldsm88** [radanalyticsio/oshinko-s2i#239]
I have a repository already set up to implement SparkPI using Scala and the Scalatra microframework:
https://github.com/reynoldsm88/tutorial-sparkpi-scala-scalatra

I've followed the directions here:
https://github.com/radanalyticsio/oshinko-s2i#using-release-templatessh

It outputs several Scala related JSON configurations:
scalabuild.json
scaladc.json
scalabuilddc.json

Could you give me a hint which one of these I should use to deploy my Scalatra SparkPI service?

Thanks,
Michael Reynolds

**Comment by elmiko** [comment]
hey Michael,

there are a couple options available for building your application. from this repository, i would use the `scalabuilddc.json` manifest and then use the template that is created. another option is to use the manifest that we host at the radanalytics.io website (`https://radanalytics.io/resources.yaml`). the resources.yaml manifest contains a template named `oshinko-scala-spark-build-dc` which is functionally equivalent to the `scalabuilddc.json` in this repository but is pinned to stable images instead of master images.

lastly, there is a scala/akka sparkpi tutorial that has not been published on the site yet, it may provide some nice reference for the work you are doing in terms of deployment options. there is a readme with some convenient instructions, check it out https://github.com/radanalyticsio/tutorial-sparkpi-scala-akka

hope that helps =)

**Comment by reynoldsm88** [comment]
@elmiko Thank you very much! That should work. I didn't see the akka-http tutorial because I had only been working from the documentation. It seemed like you were missing one using Scala so I through this together. Does the akka-http one make this one redundant? There are a few other things I was going to put in that may be different that the implementation there.

**Comment by elmiko** [comment]
> Does the akka-http one make this one redundant?

it definitely does not!

i think that having different http framework options is a great thing and only helps to show the various ways that spark can be integrated into these services. we just merged a java/vertx example alongside the java/spring one, so i would definitely cast my vote to see a few more examples. your scala+scalatra work is definitely welcome =)

**Comment by reynoldsm88** [comment]
Sounds good!

**Comment by reynoldsm88** [comment]
One last question...

I'm using SBT to build my fat jar with `sbt assembly`. I see that in the scalabuild.json I'm able to specify SBT commands that overrides default the default of `sbt package`. However, that's not in the scalabuilddc.json/oshinko-scala-spark-build-dc you suggested does not seem to have that option.

Will things still work if I use the scalabuild.json?

**Comment by reynoldsm88** [comment]
@elmiko I apologize greatly, I missed that part. I guess I didn't read that far down in the YAML file.

Give me another hour or two and once I get the application deployed we can close this issue. Thanks for pointing that out I'm not sure how I missed it.

**Comment by elmiko** [comment]
no worries @reynoldsm88 , i go a little cross-eyed after staring at too much json XD

**Comment by reynoldsm88** [comment]
@elmiko closing this as I got my app working.

I added a PR for the site with my Scalatra tutorial as well: https://github.com/radanalyticsio/radanalyticsio.github.io/pull/221

Thanks for your help!
